from __future__ import annotations

import io
import ipaddress
import re
import zipfile
from typing import Any

from .config import validate_nut_username

PLATFORMS = {"debian", "rhel", "alpine", "generic"}
POLICIES = {"inherit", "critical", "timer", "immediate", "monitor_only"}
SERVER_ADDRESS = re.compile(r"^[A-Za-z0-9_.:%-]{1,253}$")


def validate_client_profile(values: dict[str, Any]) -> dict[str, Any]:
    name = str(values.get("name", "")).strip()
    if not name or len(name) > 80 or any(char in name for char in "\r\n"):
        raise ValueError("Client name is required")
    try:
        address = str(ipaddress.ip_address(str(values.get("address", "")).strip()))
    except ValueError as error:
        raise ValueError("A valid client IP address is required") from error
    server_address = str(values.get("server_address", "")).strip()
    if not SERVER_ADDRESS.fullmatch(server_address):
        raise ValueError("A valid NUPSON server address is required")
    platform = str(values.get("platform", "debian"))
    policy = str(values.get("policy", "inherit"))
    if platform not in PLATFORMS:
        raise ValueError("Unsupported client platform")
    if policy not in POLICIES:
        raise ValueError("Unsupported shutdown policy")
    delay = int(values.get("delay_seconds", 600))
    final_delay = int(values.get("final_delay_seconds", 5))
    if not 1 <= delay <= 86400:
        raise ValueError("Shutdown delay must be between 1 and 86400 seconds")
    if not 0 <= final_delay <= 300:
        raise ValueError("Final delay must be between 0 and 300 seconds")
    return {
        "name": name,
        "address": address,
        "server_address": server_address,
        "platform": platform,
        "policy": policy,
        "delay_seconds": delay,
        "final_delay_seconds": final_delay,
    }


def render_client_files(
    profile: dict[str, Any],
    settings: dict[str, Any],
    password: str,
) -> dict[str, str]:
    if not password or any(char.isspace() or char in '"\\' for char in password):
        raise ValueError("The current NUT client password cannot be safely exported")
    policy = profile["policy"]
    if policy == "inherit":
        policy = str(settings["client_shutdown_policy"])
        delay = int(settings["client_shutdown_delay_seconds"])
        final_delay = int(settings["client_final_delay_seconds"])
    else:
        delay = int(profile["delay_seconds"])
        final_delay = int(profile["final_delay_seconds"])
    command = "/sbin/poweroff" if profile["platform"] == "alpine" else "/usr/sbin/shutdown -h now"
    shutdown_command = "/bin/true" if policy == "monitor_only" else command
    minimum_supplies = 0 if policy == "monitor_only" else 1
    monitor = (
        f"MONITOR {settings['ups_name']}@{profile['server_address']}:3493 "
        f"1 {validate_nut_username(str(settings.get('nut_client_username', 'upsmon')))} "
        f"{password} secondary"
    )
    scheduled = policy in {"timer", "immediate"}
    notify_flags = "SYSLOG+WALL+EXEC" if scheduled else "SYSLOG+WALL"
    upsmon_lines = [
        monitor,
        f"MINSUPPLIES {minimum_supplies}",
        f'SHUTDOWNCMD "{shutdown_command}"',
        "POLLFREQ 5",
        "POLLFREQALERT 2",
        "DEADTIME 25",
        "HOSTSYNC 30",
        f"FINALDELAY {final_delay}",
        f"NOTIFYFLAG ONLINE {notify_flags}",
        f"NOTIFYFLAG ONBATT {notify_flags}",
        "NOTIFYFLAG LOWBATT SYSLOG+WALL",
        "NOTIFYFLAG FSD SYSLOG+WALL",
        "NOTIFYFLAG COMMOK SYSLOG",
        "NOTIFYFLAG COMMBAD SYSLOG+WALL",
    ]
    files = {"nut.conf": "MODE=netclient\n"}
    if scheduled:
        upsmon_lines.extend(
            [
                "RUN_AS_USER nut",
                "NOTIFYCMD /usr/sbin/upssched",
            ]
        )
        action = (
            f"START-TIMER nupson-shutdown {delay}"
            if policy == "timer"
            else "EXECUTE nupson-shutdown"
        )
        files["upssched.conf"] = "\n".join(
            [
                "CMDSCRIPT /usr/local/sbin/nupson-upssched",
                "PIPEFN /run/nut/upssched.pipe",
                "LOCKFN /run/nut/upssched.lock",
                f"AT ONBATT * {action}",
                "AT ONLINE * CANCEL-TIMER nupson-shutdown",
                "",
            ]
        )
        files["nupson-upssched"] = "\n".join(
            [
                "#!/bin/sh",
                'if [ "$1" = "nupson-shutdown" ]; then',
                f"    exec /usr/bin/sudo -n {command}",
                "fi",
                "",
            ]
        )
        files["nupson-nut-shutdown.sudoers"] = "\n".join(
            [
                "# Generated by NUPSON for an early local shutdown from upssched.",
                f"nut ALL=(root) NOPASSWD: {command}",
                "",
            ]
        )
    files["upsmon.conf"] = "\n".join(upsmon_lines) + "\n"
    files["README.txt"] = _readme(profile, policy, scheduled)
    return files


def zip_client_files(files: dict[str, str]) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for name, content in files.items():
            info = zipfile.ZipInfo(name)
            mode = {
                "nupson-upssched": 0o755,
                "nupson-nut-shutdown.sudoers": 0o440,
            }.get(name, 0o640)
            info.external_attr = mode << 16
            archive.writestr(info, content)
    return buffer.getvalue()


def _readme(profile: dict[str, Any], policy: str, scheduled: bool) -> str:
    directory = "/etc/nut" if profile["platform"] != "rhel" else "/etc/ups"
    service = "nut-monitor" if profile["platform"] != "rhel" else "upsmon"
    package = {
        "debian": "apt install nut-client" + (" sudo" if scheduled else ""),
        "rhel": "dnf install nut-client" + (" sudo" if scheduled else ""),
        "alpine": "apk add nut" + (" sudo" if scheduled else ""),
        "generic": "Install the NUT client package"
        + (" and sudo" if scheduled else "")
        + " for this system",
    }[profile["platform"]]
    lines = [
        f"NUPSON client profile: {profile['name']}\n"
        f"Expected client IP: {profile['address']}\n"
        f"Shutdown policy: {policy}\n\n"
        f"1. Install NUT: {package}\n"
        f"2. Copy nut.conf and upsmon.conf to {directory}.\n"
        f"3. Protect upsmon.conf: chown root:nut {directory}/upsmon.conf && "
        f"chmod 640 {directory}/upsmon.conf\n"
    ]
    step = 4
    if scheduled:
        lines.extend(
            [
                f"{step}. Install upssched.conf: install -o root -g nut -m 0640 "
                f"upssched.conf {directory}/upssched.conf\n",
                f"{step + 1}. Install the root-owned command script: install -o root "
                "-g root -m 0755 nupson-upssched "
                "/usr/local/sbin/nupson-upssched\n",
                f"{step + 2}. Install the restricted privilege rule: install -o root "
                "-g root -m 0440 nupson-nut-shutdown.sudoers "
                "/etc/sudoers.d/nupson-nut-shutdown\n",
                f"{step + 3}. Validate it: visudo -cf /etc/sudoers.d/nupson-nut-shutdown\n",
                "The sudoers rule permits user nut to run only the exact local shutdown "
                "command generated for this profile. It is required only by the timer "
                "and immediate policies; standard critical shutdown uses upsmon's "
                "privileged process and does not need this rule.\n",
            ]
        )
        step += 4
    lines.extend(
        [
            f"{step}. Restart the service: systemctl restart {service}\n",
            f"{step + 1}. Confirm the connection in NUPSON.\n",
        ]
    )
    return "".join(lines)
