import unittest
from pathlib import Path
from subprocess import CompletedProcess, TimeoutExpired
from tempfile import TemporaryDirectory
from unittest.mock import patch

from nupson.nut import NutSupervisor, _nut_binary, parse_ups_conf


class NutParserTests(unittest.TestCase):
    def test_locates_nut_daemon_in_packaging_specific_directory(self):
        with TemporaryDirectory() as directory:
            daemon = Path(directory) / "upsd"
            daemon.touch()
            with (
                patch("nupson.nut.shutil.which", return_value=None),
                patch("nupson.nut.NUT_BINARY_DIRS", (Path(directory),)),
            ):
                self.assertEqual(_nut_binary("upsd"), str(daemon))

    def test_parses_scanner_output(self):
        result = parse_ups_conf(
            """
            # generated by nut-scanner
            [nutdev1]
                driver = "usbhid-ups"
                port = "auto"
                vendorid = "051D"
                productid = "0002"
                serial = "ABC"
            """
        )
        self.assertEqual(len(result), 1)
        self.assertEqual(result[0]["driver"], "usbhid-ups")
        self.assertEqual(result[0]["serial"], "ABC")

    def test_supervisor_preserves_actionable_usb_claim_error(self):
        with TemporaryDirectory() as directory:
            nut_dir = Path(directory)
            (nut_dir / "ups.conf").write_text("[ups]\n")
            supervisor = NutSupervisor(nut_dir, True)
            failed = CompletedProcess(
                ["upsdrvctl", "start"],
                1,
                stdout="",
                stderr="Can't claim USB device [0764:0501]@0/0: Entity not found\n",
            )
            with (
                patch("nupson.nut.subprocess.run", return_value=failed),
                patch("nupson.nut.subprocess.Popen") as popen,
            ):
                supervisor.start()
            self.assertIn("inny proces lub kontener", supervisor.startup_error or "")
            popen.assert_not_called()

    def test_driver_commands_have_hard_timeouts(self):
        with TemporaryDirectory() as directory:
            nut_dir = Path(directory)
            (nut_dir / "ups.conf").write_text("[ups]\n")
            supervisor = NutSupervisor(nut_dir, True)
            stopped = CompletedProcess(["upsdrvctl", "stop"], 0, stdout="", stderr="")
            with (
                patch(
                    "nupson.nut.subprocess.run",
                    side_effect=[
                        TimeoutExpired(["upsdrvctl", "start"], 15),
                        stopped,
                    ],
                ) as run,
                patch("nupson.nut.subprocess.Popen") as popen,
            ):
                supervisor.start()

            self.assertIn("przerwano po 15 sekundach", supervisor.startup_error or "")
            self.assertEqual(run.call_args_list[0].kwargs["timeout"], 15)
            self.assertEqual(run.call_args_list[1].kwargs["timeout"], 8)
            popen.assert_not_called()

    def test_reconfigure_stops_old_driver_before_writing_new_config(self):
        supervisor = NutSupervisor(Path("/unused"), True)
        calls = []

        with (
            patch.object(supervisor, "stop", side_effect=lambda: calls.append("stop")),
            patch.object(supervisor, "start", side_effect=lambda: calls.append("start")),
        ):
            result = supervisor.reconfigure(lambda: calls.append("write") or "written")

        self.assertEqual(result, "written")
        self.assertEqual(calls, ["stop", "write", "start"])

    def test_reconfigure_clients_keeps_usb_driver_running(self):
        with TemporaryDirectory() as directory:
            nut_dir = Path(directory)
            (nut_dir / "ups.conf").write_text("[ups]\n")
            supervisor = NutSupervisor(nut_dir, True)
            calls = []
            with (
                patch.object(
                    supervisor, "_stop_servers", side_effect=lambda: calls.append("stop-servers")
                ),
                patch.object(
                    supervisor,
                    "_start_servers",
                    side_effect=lambda environment: calls.append("start-servers"),
                ),
            ):
                supervisor.reconfigure_clients(lambda: calls.append("write"))

            self.assertEqual(calls, ["stop-servers", "write", "start-servers"])


if __name__ == "__main__":
    unittest.main()
