const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const escapeHtml = (value) => String(value ?? "").replace(/[&<>'"]/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const api = async (path, options = {}) => {
  const response = await fetch(path, {credentials:"same-origin", headers:{"Content-Type":"application/json", ...(options.headers||{})}, ...options});
  const data = response.status === 204 ? {} : await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`);
  return data;
};
let state = {status:null, hosts:[], events:[], settings:{}, clientProfiles:[], unrecognizedClients:[], clientConfigFiles:{}, clientConfigProfile:null, setup:false};
let historyLoading = false;
let hostsLoading = false;
let clientProfilesLoading = false;
let webhookScenariosLoaded = false;
let eventSource = null;
let lastBackendEvent = Date.now();
let backendConnected = true;
let backendRecoveryRunning = false;
let backendBannerTimer = null;

function toast(message) { const node=$("#toast"); node.textContent=message; node.classList.remove("hidden"); setTimeout(()=>node.classList.add("hidden"),3000); }
function markBackendOffline() {
  if(!$("#app").classList.contains("hidden")){
    const banner=$("#backend-banner");banner.classList.remove("hidden","reconnected");banner.querySelector("strong").textContent="Połączenie z NUPSON zostało przerwane";banner.querySelector("span").textContent="Wyświetlane dane mogą być nieaktualne. Trwa automatyczne ponowne łączenie…";
  }
  backendConnected=false;
}
function markBackendRecovered() {
  const wasDisconnected=!backendConnected;backendConnected=true;lastBackendEvent=Date.now();
  if(!wasDisconnected)return;
  const banner=$("#backend-banner");banner.classList.remove("hidden");banner.classList.add("reconnected");banner.querySelector("strong").textContent="Połączenie przywrócone";banner.querySelector("span").textContent="Wszystkie dane zostały pobrane ponownie.";
  clearTimeout(backendBannerTimer);backendBannerTimer=setTimeout(()=>{if(backendConnected)banner.classList.add("hidden");},2500);
}
function showLoginAfterSessionExpiry() {
  if(eventSource){eventSource.close();eventSource=null;}
  $("#app").classList.add("hidden");$("#auth").classList.remove("hidden");$("#auth-title").textContent="Zaloguj się";$("#auth-copy").textContent="Sesja wygasła. Zaloguj się ponownie, aby pobrać aktualne dane.";$("#auth-form [name=password]").autocomplete="current-password";$("#auth-error").textContent="";
}
async function recoverBackend() {
  if(backendRecoveryRunning||$("#app").classList.contains("hidden"))return;
  backendRecoveryRunning=true;
  try{
    const response=await fetch("/api/auth/status",{credentials:"same-origin",cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);const auth=await response.json();
    if(!auth.authenticated){showLoginAfterSessionExpiry();return;}
    await loadAll();
    if($("#view-statistics").classList.contains("active"))await loadHistory();
    if($("#view-settings").classList.contains("active"))await refreshRaw();
    markBackendRecovered();
  }catch(_error){markBackendOffline();}
  finally{backendRecoveryRunning=false;}
}
function setButtonBusy(button,busy,label="Przetwarzanie…") { const text=button.querySelector("span"); if(busy){button.dataset.label=text?text.textContent:button.textContent;button.disabled=true;button.classList.add("is-loading");if(text)text.textContent=label;else button.textContent=label;}else{button.disabled=false;button.classList.remove("is-loading");const original=button.dataset.label;if(original){if(text)text.textContent=original;else button.textContent=original;delete button.dataset.label;}} }
function formatDuration(seconds) { if(seconds==null||isNaN(seconds))return "—"; const s=Number(seconds); const h=Math.floor(s/3600),m=Math.floor(s%3600/60); return h?`${h} h ${m} min`:`${m} min`; }
function formatCountdown(seconds) { const s=Math.max(0,Number(seconds)||0); return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`; }
function statusInfo(status) {
  const tokens=(status||"").split(" ");
  if(tokens.includes("COMMLOST")||tokens.includes("STALE")||!status)return ["error","Brak komunikacji","Sprawdź połączenie USB i proces sterownika NUT."];
  if(tokens.includes("OB"))return ["battery",tokens.includes("LB")?"Niska bateria":"Praca na baterii",tokens.includes("LB")?"Klienci NUT przygotowują się do wyłączenia.":"Zarejestrowano zanik zasilania sieciowego."];
  if(tokens.includes("OL"))return ["online",tokens.includes("CHRG")?"Zasilanie sieciowe · ładowanie":"Zasilanie sieciowe","UPS pracuje poprawnie z sieci energetycznej."];
  return ["unknown","Stan nierozpoznany",status];
}
function renderStatus(data) {
  state.status=data; const raw=data.ups||{}; const info=statusInfo(raw["ups.status"]||data.connection_error&&"COMMLOST");
  const powerState=data.power_state||"normal"; const recovering=powerState==="recovery_pending"; const waitingForCharge=powerState==="waiting_for_charge"; const waking=powerState==="waking"; const wakeCount=Number(data.wake_host_count)||0; const statusTokens=(raw["ups.status"]||"").split(" "); const onBattery=statusTokens.includes("OB");
  const hero=$("#power-hero"); hero.className=`power-hero ${info[0]} state-${powerState}`;
  let label=info[1],detail=info[2],phase="SIEĆ",actionLabel="",actionValue="";
  if(data.connection_error){phase="BRAK ŁĄCZNOŚCI";}
  else if(recovering){phase="POTWIERDZANIE ZASILANIA";label="Zasilanie wróciło — sprawdzamy jego ciągłość";detail=wakeCount?`Krok 1 z 2: czekamy, czy prąd nie zaniknie ponownie. Potem sprawdzimy baterię przed uruchomieniem ${wakeCount} hostów.`:"Czekamy, czy prąd nie zaniknie ponownie. Brak hostów oczekujących na WoL.";actionLabel="Do potwierdzenia ciągłości";actionValue=formatCountdown(data.remaining_seconds);}
  else if(waitingForCharge){const minimum=Number(data.minimum_charge)||0;phase="ŁADOWANIE BATERII";label="Zasilanie jest stabilne — czekamy na baterię";detail=wakeCount?`Krok 2 z 2: uruchamianie ${wakeCount} hostów rozpocznie się po osiągnięciu ustawionego zapasu baterii.`:`Zasilanie zostało potwierdzone. Brak hostów oczekujących na WoL.`;actionLabel="Bateria / wymagane minimum";actionValue=`${Number.isFinite(Number(raw["battery.charge"]))?`${raw["battery.charge"]}%`:"—"} / ${minimum}%`;}
  else if(waking){phase="URUCHAMIANIE";label="Zasilanie jest stabilne";detail="Trwa sprawdzanie hostów i wykonywanie kolejki Wake-on-LAN.";actionLabel="Hosty w sekwencji";actionValue=String(wakeCount);}
  else if(onBattery){phase=statusTokens.includes("LB")?"NISKA BATERIA":"AWARIA SIECI";actionLabel="Szacowany czas pracy";actionValue=formatDuration(raw["battery.runtime"]);}
  else if(info[0]==="unknown"){phase="NIEZNANY";}
  $("#power-phase").textContent=phase; $("#power-label").textContent=label; $("#power-detail").textContent=data.connection_error||detail;
  const action=$("#recovery-box"); action.classList.toggle("hidden",!actionLabel); $("#power-action-label").textContent=actionLabel; $("#recovery-time").textContent=actionValue;
  const progress=$("#power-progress"); const total=Math.max(1,Number(data.stabilization_seconds)||1); const remaining=Math.max(0,Number(data.remaining_seconds)||0); const charge=Number(raw["battery.charge"]); const minimum=Math.max(1,Number(data.minimum_charge)||1); progress.classList.toggle("hidden",!recovering&&!waitingForCharge); progress.style.width=recovering?`${Math.min(100,remaining/total*100)}%`:waitingForCharge&&Number.isFinite(charge)?`${Math.min(100,charge/minimum*100)}%`:"0";
  const battery=Number(raw["battery.charge"]); $("#battery").textContent=Number.isFinite(battery)?`${battery}%`:"—"; $("#battery-bar").style.width=`${Math.max(0,Math.min(100,battery||0))}%`;
  $("#runtime").textContent=formatDuration(raw["battery.runtime"]); $("#runtime-note").textContent=onBattery?"bieżący szacunek przy pracy z baterii":"szacunek UPS; po przejściu na baterię może się zmienić"; const load=Number(raw["ups.load"]); $("#load").textContent=Number.isFinite(load)?`${load}%`:"—"; $("#load-bar").style.width=`${Math.max(0,Math.min(100,load||0))}%`;
  const watts=data.power_usage_watts==null?NaN:Number(data.power_usage_watts); $("#power-usage").textContent=Number.isFinite(watts)?`${watts} W`:"—"; $("#power-usage-note").textContent=data.power_usage_estimated?"szacunek z obciążenia i mocy znamionowej":"wartość raportowana przez UPS";
  $("#voltage").textContent=raw["input.voltage"]?`${raw["input.voltage"]} V`:"—"; $("#output-voltage").textContent=raw["output.voltage"]?`wyjście ${raw["output.voltage"]} V`:"wyjście —";
  $("#connection-dot").classList.toggle("ok",!data.connection_error); $("#connection-label").textContent=data.connection_error?"UPS niedostępny":"NUT połączony";
}
function renderMiniChart(selector,points,series,bounds={}) {
  const valid=value=>value!==null&&value!==""&&Number.isFinite(Number(value));const node=$(selector);const usable=series.filter(item=>points.some(point=>valid(point[item.key])));
  if(!points.length||!usable.length){node.innerHTML='<div class="chart-empty">Brak danych dla tego zakresu</div>';return;}
  const values=usable.flatMap(item=>points.map(point=>point[item.key]).filter(valid).map(Number));let min=bounds.min??Math.min(...values),max=bounds.max??Math.max(...values);if(min===max){min-=1;max+=1;}
  const width=600,height=160,left=48,right=8,top=8,bottom=28,first=Number(points[0].timestamp),last=Number(points.at(-1).timestamp),span=Math.max(1,last-first);const x=t=>left+(Number(t)-first)/span*(width-left-right);const y=value=>top+(max-Number(value))/(max-min)*(height-top-bottom);const axis=value=>`${Number(value).toLocaleString("pl-PL",{maximumFractionDigits:bounds.digits??0})}${bounds.unit||""}`;const time=value=>new Date(value*1000).toLocaleString("pl-PL",span<=86400?{hour:"2-digit",minute:"2-digit"}:{day:"2-digit",month:"2-digit"});
  const lines=usable.map(item=>{let drawing=false,d="";for(const point of points){const raw=point[item.key];if(!valid(raw)){drawing=false;continue;}const value=Number(raw);d+=`${drawing?"L":"M"}${x(point.timestamp).toFixed(1)},${y(value).toFixed(1)} `;drawing=true;}return `<path class="chart-line" stroke="${item.color}" d="${d.trim()}"></path>`;}).join("");
  const yTicks=[max,(max+min)/2,min].map(value=>`<g><line class="chart-grid-line" x1="${left}" y1="${y(value).toFixed(1)}" x2="${width-right}" y2="${y(value).toFixed(1)}"></line><text class="chart-axis-label" x="${left-6}" y="${(y(value)+4).toFixed(1)}" text-anchor="end">${axis(value)}</text></g>`).join("");const xTicks=[first,first+span/2,last].map((value,index)=>`<text class="chart-axis-label" x="${x(value).toFixed(1)}" y="${height-5}" text-anchor="${index===0?"start":index===2?"end":"middle"}">${time(value)}</text>`).join("");
  const legend=usable.map(item=>`<span><i style="background:${item.color}"></i>${escapeHtml(item.label)}</span>`).join("");node.innerHTML=`<svg viewBox="0 0 ${width} ${height}" role="img">${yTicks}${xTicks}${lines}</svg><div class="chart-legend">${legend}</div>`;
}
function renderHistory(data){const points=data.points||[],summary=data.summary||{};const number=(value,digits=0)=>value!==null&&value!==""&&Number.isFinite(Number(value))?Number(value).toLocaleString("pl-PL",{minimumFractionDigits:digits,maximumFractionDigits:digits}):"—";$("#history-energy").textContent=`${number(summary.energy_kwh,3)} kWh`;$("#history-cost").textContent=`${number(summary.energy_cost,2)} ${summary.currency||"PLN"}`;$("#history-average-power").textContent=`${number(summary.average_power_watts)} W`;$("#history-peak-power").textContent=`${number(summary.peak_power_watts)} W`;renderMiniChart("#chart-percent",points,[{key:"battery_charge",label:"Bateria",color:"#43d17a"},{key:"load_percent",label:"Obciążenie",color:"#f4c95d"}],{min:0,max:100,unit:"%"});renderMiniChart("#chart-voltage",points,[{key:"input_voltage",label:"Napięcie wejściowe",color:"#5ba7ff"},{key:"output_voltage",label:"Napięcie wyjściowe",color:"#43d17a"}],{unit:" V"});renderMiniChart("#chart-power",points,[{key:"power_watts",label:"Pobór mocy",color:"#f4c95d"}],{min:0,unit:" W"});const runtimePoints=points.map(point=>({...point,runtime_minutes:point.runtime_seconds==null?null:Number(point.runtime_seconds)/60}));renderMiniChart("#chart-runtime",runtimePoints,[{key:"runtime_minutes",label:"Pozostały czas",color:"#b58cff"}],{min:0,unit:" min"});const from=new Date(data.from*1000).toLocaleString("pl-PL"),to=new Date(data.to*1000).toLocaleString("pl-PL");$("#history-note").textContent=`${summary.sample_count||0} próbek · agregacja ${formatDuration(data.bucket_seconds)} · ${from} – ${to} · koszt orientacyjny na podstawie mocy UPS`;} 
function historyDates(){const choice=$("#history-range").value;if(choice==="custom"){const from=new Date($("#history-from").value).getTime()/1000,to=new Date($("#history-to").value).getTime()/1000;if(!Number.isFinite(from)||!Number.isFinite(to)||to<=from)throw new Error("Wybierz poprawny zakres dat");return {from:Math.floor(from),to:Math.floor(to)};}const to=Math.floor(Date.now()/1000);return {from:to-Number(choice),to};}
async function loadHistory(button=null){if(historyLoading)return;historyLoading=true;if(button)setButtonBusy(button,true,"Odświeżanie…");try{const range=historyDates();const data=await api(`/api/history?from=${range.from}&to=${range.to}`);renderHistory(data);}catch(error){toast(error.message);}finally{historyLoading=false;if(button)setButtonBusy(button,false);}}
function renderHosts() {
  const rows=state.hosts; $("#hosts-list").innerHTML=rows.length?rows.map(h=>{const verification=h.address?`weryfikacja ping: ${escapeHtml(h.address)}`:"bez weryfikacji startu";return `<article class="host-card"><div><span class="status-pill ${h.last_online?'ok':''}">${h.last_online?'potwierdzony online':'offline / niepotwierdzony'}</span><h3>${escapeHtml(h.name)}</h3><p>${escapeHtml(h.mac)} · fala ${h.wave} · ${escapeHtml(h.policy)}</p><p>${verification}</p></div><div><button class="secondary wake-host" data-id="${h.id}">Obudź</button> <button class="secondary edit-host" data-id="${h.id}">Edytuj</button> <button class="danger delete-host" data-id="${h.id}">Usuń</button></div></article>`;}).join(""):"<div class='panel empty'>Nie dodano jeszcze hostów Wake-on-LAN.</div>";
  $("#dashboard-hosts").innerHTML=rows.length?rows.slice(0,5).map(h=>`<div class="list-row"><strong>${escapeHtml(h.name)}</strong><span>${h.last_online?'online':`fala ${h.wave}`}</span></div>`).join(""):"Brak hostów WoL.";
}
function renderEvents() {
  const html=state.events.map(e=>`<div class="event ${escapeHtml(e.level)}"><i class="event-dot"></i><div class="event-copy"><p>${escapeHtml(e.message)}</p><small>${escapeHtml(e.kind)}</small></div><time>${new Date(e.created_at).toLocaleString("pl-PL")}</time></div>`).join("");
  $("#events-list").innerHTML=html||"Brak zdarzeń."; $("#dashboard-events").innerHTML=html?state.events.slice(0,5).map(e=>`<div class="event ${escapeHtml(e.level)}"><i class="event-dot"></i><div class="event-copy"><p>${escapeHtml(e.message)}</p></div><time>${new Date(e.created_at).toLocaleTimeString("pl-PL",{hour:"2-digit",minute:"2-digit"})}</time></div>`).join(""):"Brak zdarzeń.";
}
function clientPolicyLabel(policy) { return ({inherit:"Dziedziczy ustawienia globalne",critical:"Krytyczny stan UPS / FSD",timer:"Wyłączenie po czasie",immediate:"Natychmiast po zaniku",monitor_only:"Tylko monitorowanie"})[policy]||policy; }
function renderClientProfiles() {
  const statusLabel={connected:"Połączony",disconnected:"Rozłączony",waiting:"Oczekuje"};
  $("#client-profiles").innerHTML=state.clientProfiles.length?state.clientProfiles.map(profile=>{
    const seen=profile.last_seen?` · ostatnio ${new Date(profile.last_seen).toLocaleString("pl-PL")}`:"";
    const config=profile.config_current?"Paczka wygenerowana":"Wymaga wygenerowania paczki";
    return `<article class="client-profile-card"><div class="client-profile-main"><span class="status-pill ${profile.status==='connected'?'ok':profile.status==='disconnected'?'warning':''}">${statusLabel[profile.status]}</span><h3>${escapeHtml(profile.name)}</h3><p>${escapeHtml(profile.address)}${escapeHtml(seen)}</p><p>${escapeHtml(clientPolicyLabel(profile.policy))} · ${escapeHtml(config)}</p></div><div class="client-profile-actions"><button class="secondary preview-client" data-id="${profile.id}"><i class="ti ti-settings"></i><span>Podgląd</span></button><button class="primary download-client" data-id="${profile.id}"><i class="ti ti-download"></i><span>Pobierz ZIP</span></button><button class="secondary edit-client" data-id="${profile.id}">Edytuj</button><button class="danger delete-client" data-id="${profile.id}">Usuń</button></div></article>`;
  }).join(""):"<div class='panel empty'>Nie utworzono jeszcze profilu klienta NUT.</div>";
  const panel=$("#unrecognized-clients-panel");panel.classList.toggle("hidden",!state.unrecognizedClients.length);
  $("#unrecognized-clients").innerHTML=state.unrecognizedClients.map(address=>`<div class="list-row"><strong>${escapeHtml(address)}</strong><button class="secondary create-client-from-address" data-address="${escapeHtml(address)}">Utwórz profil</button></div>`).join("");
}
async function refreshHosts() { if(hostsLoading)return;hostsLoading=true;try{state.hosts=await api("/api/hosts");renderHosts();}finally{hostsLoading=false;} }
async function refreshClientProfiles() { if(clientProfilesLoading)return;clientProfilesLoading=true;try{const data=await api("/api/client-profiles");state.clientProfiles=data.profiles||[];state.unrecognizedClients=data.unrecognized||[];renderClientProfiles();}finally{clientProfilesLoading=false;} }
function renderUpsConfiguration(config,clientUsername=state.settings?.nut_client_username||"upsmon") { const configured=Boolean(config);const status=$("#ups-config-status");status.classList.toggle("ok",configured);status.textContent=configured?`Aktywna: ${config.name} · ${config.driver}`:"Nieskonfigurowano";if(config){Object.entries(config).forEach(([k,v])=>{const field=$(`#ups-form [name="${k}"]`);if(field)field.value=v;});}else{$("#ups-form").reset();}$("#ups-form [name=client_username]").value=clientUsername;const password=$("#ups-form [name=client_password]");password.required=!configured;$("#client-password-label").textContent=configured?"Nowe hasło klientów NUT (opcjonalnie)":"Hasło klientów NUT";$("#delete-ups-config").classList.toggle("hidden",!configured); }
async function loadAll() { const [status,hosts,events,settings,clients]=await Promise.all([api("/api/status"),api("/api/hosts"),api("/api/events?limit=100"),api("/api/settings"),api("/api/client-profiles")]); state={...state,status,hosts,events,settings,clientProfiles:clients.profiles||[],unrecognizedClients:clients.unrecognized||[]};renderStatus(status);renderHosts();renderEvents();renderClientProfiles();["#automation-form","#webhook-form","#history-settings-form","#shutdown-policy-form"].forEach(selector=>Object.entries(settings).forEach(([k,v])=>{const f=$(`${selector} [name="${k}"]`);if(f)f.value=v;}));syncGlobalClientDelayField();renderUpsConfiguration(settings.ups_config,settings.nut_client_username);$("#onboarding").classList.toggle("hidden",status.configured); }
function route() { let view=(location.hash||"#dashboard").slice(1);if(view==="ups")view="settings";const valid=$("#view-"+view)?view:"dashboard"; $$(".view").forEach(x=>x.classList.toggle("active",x.id===`view-${valid}`)); $$('nav a').forEach(x=>x.classList.toggle("active",x.dataset.view===valid)); $("#page-title").textContent=({dashboard:"Przegląd",statistics:"Statystyki",hosts:"Hosty",clients:"Klienci NUT",events:"Zdarzenia",settings:"Ustawienia"})[valid];if(valid==="events")refreshEvents();if(valid==="statistics")loadHistory();if(valid==="settings")refreshRaw();if(valid==="clients")refreshClientProfiles().catch(error=>toast(error.message)); }
async function init() { const auth=await api("/api/auth/status"); if(!auth.authenticated){state.setup=auth.setup_required;$("#auth").classList.remove("hidden");$("#auth-title").textContent=state.setup?"Witaj w NUPSON":"Zaloguj się";$("#auth-copy").textContent=state.setup?"Utwórz konto administratora, aby rozpocząć konfigurację.":"Zaloguj się do panelu zarządzania.";$("#auth-form [name=password]").autocomplete=state.setup?"new-password":"current-password";return;} $("#app").classList.remove("hidden");await loadAll();lastBackendEvent=Date.now();history.replaceState(null,"",`${location.pathname}${location.search}${state.status.configured?"#dashboard":"#settings"}`);route();connectEvents(); }
function connectEvents(){
  if(eventSource)eventSource.close();eventSource=new EventSource("/api/stream");
  eventSource.addEventListener("open",()=>{lastBackendEvent=Date.now();if(!backendConnected)recoverBackend();});
  eventSource.addEventListener("status",e=>{lastBackendEvent=Date.now();const wasDisconnected=!backendConnected;renderStatus(JSON.parse(e.data));if(wasDisconnected)recoverBackend();if($("#view-clients").classList.contains("active"))refreshClientProfiles().catch(()=>{});if($("#view-hosts").classList.contains("active")||$("#view-dashboard").classList.contains("active"))refreshHosts().catch(()=>{});});
  eventSource.onerror=()=>markBackendOffline();
}
async function refreshEvents(button=null){if(button)setButtonBusy(button,true,"Odświeżanie…");try{state.events=await api("/api/events?limit=100");renderEvents();if(button)toast("Lista zdarzeń odświeżona");}catch(error){toast(error.message);}finally{if(button)setButtonBusy(button,false);}}
const nutLabels={"ups.status":"Stan UPS","battery.charge":"Naładowanie","battery.runtime":"Raportowany czas pracy","battery.voltage":"Napięcie baterii","battery.voltage.nominal":"Napięcie znamionowe baterii","battery.charge.low":"Próg niskiej baterii","battery.charge.warning":"Próg ostrzeżenia","battery.runtime.low":"Próg krótkiego czasu pracy","battery.type":"Typ baterii","battery.mfr.date":"Dane producenta baterii","ups.test.result":"Ostatni test baterii","ups.load":"Obciążenie","ups.realpower":"Moc czynna","ups.realpower.nominal":"Moc znamionowa","input.voltage":"Napięcie wejściowe","input.voltage.nominal":"Znamionowe napięcie wejściowe","output.voltage":"Napięcie wyjściowe","device.mfr":"Producent","device.model":"Model","ups.beeper.status":"Sygnalizator dźwiękowy"};
function nutGroup(key){if(key.startsWith("battery.")||key==="ups.test.result")return "Bateria";if(["ups.load","ups.realpower","ups.realpower.nominal","ups.power","ups.power.nominal"].includes(key)||key.startsWith("input.")||key.startsWith("output."))return "Zasilanie i obciążenie";if(key.startsWith("device.")||["ups.mfr","ups.model","ups.vendorid","ups.productid","ups.serial"].includes(key))return "Urządzenie";if(key.startsWith("driver."))return "Sterownik NUT";return "Stan i funkcje UPS";}
function nutValue(key,value){const number=Number(value);if(key==="battery.runtime"||key==="battery.runtime.low")return `${formatDuration(number)} (${escapeHtml(value)} s)`;if(key.includes("voltage")&&Number.isFinite(number))return `${escapeHtml(value)} V`;if((key.includes("charge")||key==="ups.load")&&Number.isFinite(number))return `${escapeHtml(value)}%`;if(key.includes("realpower")&&Number.isFinite(number))return `${escapeHtml(value)} W`;return escapeHtml(value);}
function renderRawDiagnostics(values,health){const order=["Bateria","Zasilanie i obciążenie","Stan i funkcje UPS","Urządzenie","Sterownik NUT"];const groups={};Object.entries(values).sort().forEach(([key,value])=>{const group=nutGroup(key);(groups[group]??=[]).push([key,value]);});$("#raw-vars").innerHTML=order.filter(group=>groups[group]?.length).map(group=>`<section class="diagnostic-group"><h4>${group}</h4><div class="raw-grid">${groups[group].map(([key,value])=>`<div class="raw-item"><span>${escapeHtml(nutLabels[key]||key)}</span><strong>${nutValue(key,value)}</strong><small>${escapeHtml(key)}</small></div>`).join("")}</div></section>`).join("")||"<p class='empty'>Brak danych UPS.</p>";const level=health?.status||"unknown";$("#battery-health").className=`battery-health ${level}`;$("#battery-health").innerHTML=`<strong>${level==="warning"?"Wymagana kontrola baterii":level==="ok"?"Test baterii bez zgłoszonego błędu":"Brak bezpośredniego pomiaru kondycji"}</strong><span>${escapeHtml(health?.summary||"Ten UPS nie udostępnia pola battery.health; NUPSON pokazuje tylko dane przekazane przez firmware.")}</span>`;}
async function refreshRaw(button=null){if(button)setButtonBusy(button,true,"Odświeżanie…");try{const [values,status]=await Promise.all([api("/api/ups/raw"),api("/api/status")]);state.status=status;renderRawDiagnostics(values,status.battery_health);if(button)toast("Dane UPS odświeżone");}catch(error){toast(error.message);}finally{if(button)setButtonBusy(button,false);}}

$("#auth-form").addEventListener("submit",async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{await api(state.setup?"/api/auth/setup":"/api/auth/login",{method:"POST",body:JSON.stringify(data)});location.reload();}catch(err){$("#auth-error").textContent=err.message;}});
$("#logout").addEventListener("click",async()=>{await api("/api/auth/logout",{method:"POST",body:"{}"});location.reload();});
function applyTheme(theme){document.documentElement.dataset.theme=theme;const light=theme==="light";$("#theme-icon").className=`ti ${light?"ti-moon":"ti-sun"}`;const label=light?"Włącz ciemny motyw":"Włącz jasny motyw";$("#theme-label").textContent=label;$("#theme-toggle").title=label;$("#theme-toggle").setAttribute("aria-label",label);}
const savedTheme=localStorage.getItem("nupson-theme")||"dark";applyTheme(savedTheme);$("#theme-toggle").addEventListener("click",()=>{const theme=document.documentElement.dataset.theme==="dark"?"light":"dark";applyTheme(theme);localStorage.setItem("nupson-theme",theme);});
function activateSettingsTab(name){$$('[data-settings-panel]').forEach(panel=>panel.classList.toggle("hidden",panel.dataset.settingsPanel!==name));$$('[data-settings-tab]').forEach(tab=>tab.classList.toggle("active",tab.dataset.settingsTab===name));if(name==="ups")refreshRaw();}
$$("[data-settings-tab]").forEach(tab=>tab.addEventListener("click",()=>activateSettingsTab(tab.dataset.settingsTab)));
window.addEventListener("hashchange",route);$("#refresh-events").addEventListener("click",e=>refreshEvents(e.currentTarget));$("#refresh-raw").addEventListener("click",e=>refreshRaw(e.currentTarget));
$("#refresh-history").addEventListener("click",e=>loadHistory(e.currentTarget));
$("#history-range").addEventListener("change",e=>{const custom=e.target.value==="custom",live=e.target.value==="3600";$("#history-custom").classList.toggle("hidden",!custom);$("#history-live").classList.toggle("hidden",!live);if(custom){const now=new Date(),before=new Date(now.getTime()-86400000);const local=value=>new Date(value.getTime()-value.getTimezoneOffset()*60000).toISOString().slice(0,16);$("#history-from").value=local(before);$("#history-to").value=local(now);}else loadHistory();});
$("#history-custom").addEventListener("submit",e=>{e.preventDefault();loadHistory(e.target.querySelector('button[type="submit"]'));});
$("#scan-ups").addEventListener("click",async()=>{const button=$("#scan-ups");setButtonBusy(button,true,"Skanowanie…");try{const devices=await api("/api/ups/scan");$("#scan-results").innerHTML=devices.length?devices.map((d,i)=>`<article class="device-card"><div><h3>${escapeHtml(d.desc||d.name||"Wykryty UPS")}</h3><p>${escapeHtml(d.driver)} · VID ${escapeHtml(d.vendorid||"—")} · PID ${escapeHtml(d.productid||"—")}</p></div><button class="secondary choose-ups" data-index="${i}">Wybierz</button></article>`).join(""):"<div class='panel empty'>Nie znaleziono zgodnego urządzenia USB.</div>";state.devices=devices;toast(devices.length?`Wykryto urządzenia: ${devices.length}`:"Nie znaleziono urządzeń USB");}catch(err){toast(err.message);}finally{setButtonBusy(button,false);}});
$("#scan-results").addEventListener("click",e=>{const b=e.target.closest(".choose-ups");if(!b)return;const d=state.devices[Number(b.dataset.index)];Object.entries(d).forEach(([k,v])=>{const f=$(`#ups-form [name="${k}"]`);if(f)f.value=v;});$("#ups-form").scrollIntoView({behavior:"smooth"});});
$("#delete-ups-config").addEventListener("click",async()=>{if(!confirm("Usunąć konfigurację UPS? Serwer i sterownik NUT zostaną zatrzymane, a paczki klientów będą wymagały ponownego wygenerowania."))return;const button=$("#delete-ups-config");setButtonBusy(button,true,"Usuwanie…");try{await api("/api/ups/configuration",{method:"DELETE"});state.settings.ups_config=null;state.settings.nut_client_username="upsmon";renderUpsConfiguration(null,"upsmon");$("#ups-message").textContent="Konfiguracja usunięta. Możesz teraz wykryć i skonfigurować inny UPS.";$("#onboarding").classList.remove("hidden");await refreshClientProfiles();toast("Konfiguracja UPS została usunięta");}catch(error){toast(error.message);}finally{setButtonBusy(button,false);}});
$("#ups-form").addEventListener("submit",async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const button=e.target.querySelector('button[type="submit"]');setButtonBusy(button,true,"Uruchamianie NUT…");$("#ups-message").textContent="Zapisywanie konfiguracji i uruchamianie sterownika…";try{const result=await api("/api/ups/configure",{method:"POST",body:JSON.stringify(data)});$("#ups-message").textContent=result.ready?"Konfiguracja aktywna — UPS odpowiada.":result.initializing?"Konfiguracja zapisana — sterownik inicjalizuje telemetrię UPS.":`Konfiguracja zapisana, ale sterownik nie wystartował: ${result.readiness_error||"brak odpowiedzi"}`;e.target.elements.client_password.value="";state.settings.ups_config=result.ups;state.settings.nut_client_username=result.client_username;renderUpsConfiguration(result.ups,result.client_username);$("#onboarding").classList.add("hidden");refreshClientProfiles().catch(()=>{});toast(result.ready?"Konfiguracja NUT została zapisana":result.initializing?"Sterownik inicjalizuje dane UPS":"Sterownik NUT nie wystartował");}catch(err){$("#ups-message").textContent=err.message;}finally{setButtonBusy(button,false);}});
$("#add-host").addEventListener("click",()=>{$("#host-form").reset();$("#host-form [name=id]").value="";$("#host-form").classList.remove("hidden");$("#host-form-title").textContent="Nowy host";});$("#cancel-host").addEventListener("click",()=>$("#host-form").classList.add("hidden"));
$("#hosts-list").addEventListener("click",async e=>{const b=e.target.closest("button");if(!b)return;const id=Number(b.dataset.id),host=state.hosts.find(h=>h.id===id);try{if(b.classList.contains("wake-host")){await api(`/api/hosts/${id}/wake`,{method:"POST",body:"{}"});toast(`Wysłano WoL do ${host.name}`);}if(b.classList.contains("delete-host")){if(confirm(`Usunąć ${host.name}?`)){await api(`/api/hosts/${id}`,{method:"DELETE"});state.hosts=await api("/api/hosts");renderHosts();}}if(b.classList.contains("edit-host")){Object.entries(host).forEach(([k,v])=>{const f=$(`#host-form [name="${k}"]`);if(f)f.value=v??"";});$("#host-form-title").textContent=`Edycja: ${host.name}`;$("#host-form").classList.remove("hidden");}}catch(err){toast(err.message);}});
$("#host-form").addEventListener("submit",async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.wave=Number(data.wave);data.delay_seconds=Number(data.delay_seconds);const id=data.id;delete data.id;try{await api(id?`/api/hosts/${id}`:"/api/hosts",{method:"POST",body:JSON.stringify(data)});state.hosts=await api("/api/hosts");renderHosts();e.target.classList.add("hidden");toast("Host zapisany");}catch(err){$("#host-message").textContent=err.message;}});
function syncClientProfileDelayField() { const policy=$("#client-profile-form [name=policy]").value;$("#client-profile-delay-field").classList.toggle("hidden",policy!=="timer"); }
function syncGlobalClientDelayField() { const policy=$("#shutdown-policy-form [name=client_shutdown_policy]").value;$("#global-client-delay-field").classList.toggle("hidden",policy!=="timer"); }
function openClientProfileForm(profile=null,address="") { const form=$("#client-profile-form");form.reset();form.elements.id.value=profile?.id||"";form.elements.server_address.value=profile?.server_address||location.hostname;form.elements.address.value=profile?.address||address;form.elements.delay_seconds.value=profile?.delay_seconds??state.settings.client_shutdown_delay_seconds??600;form.elements.final_delay_seconds.value=profile?.final_delay_seconds??state.settings.client_final_delay_seconds??5;if(profile){["name","platform","policy"].forEach(key=>form.elements[key].value=profile[key]);}syncClientProfileDelayField();$("#client-profile-title").textContent=profile?`Edycja: ${profile.name}`:"Nowy klient NUT";$("#client-profile-message").textContent="";form.classList.remove("hidden");form.scrollIntoView({behavior:"smooth",block:"start"});}
$("#add-client-profile").addEventListener("click",()=>openClientProfileForm());
$("#cancel-client-profile").addEventListener("click",()=>$("#client-profile-form").classList.add("hidden"));
$("#client-profile-form [name=policy]").addEventListener("change",syncClientProfileDelayField);
$("#shutdown-policy-form [name=client_shutdown_policy]").addEventListener("change",syncGlobalClientDelayField);
$("#client-profile-form").addEventListener("submit",async e=>{e.preventDefault();const button=e.target.querySelector('button[type="submit"]');setButtonBusy(button,true,"Zapisywanie…");const data=Object.fromEntries(new FormData(e.target));const id=data.id;delete data.id;data.delay_seconds=Number(data.delay_seconds);data.final_delay_seconds=Number(data.final_delay_seconds);try{await api(id?`/api/client-profiles/${id}`:"/api/client-profiles",{method:"POST",body:JSON.stringify(data)});e.target.classList.add("hidden");await refreshClientProfiles();toast("Profil klienta zapisany");}catch(error){$("#client-profile-message").textContent=error.message;}finally{setButtonBusy(button,false);}});
async function showClientConfiguration(id) { const data=await api(`/api/client-profiles/${id}/config`);state.clientConfigFiles=data.files||{};state.clientConfigProfile=data.profile;const select=$("#client-config-file");select.innerHTML=Object.keys(state.clientConfigFiles).map(name=>`<option value="${escapeHtml(name)}">${escapeHtml(name)}</option>`).join("");$("#client-config-preview-title").textContent=`Pliki: ${data.profile.name}`;$("#client-config-content").textContent=state.clientConfigFiles[select.value]||"";$("#client-config-preview").classList.remove("hidden");$("#client-config-preview").scrollIntoView({behavior:"smooth",block:"start"});await refreshClientProfiles();}
$("#client-profiles").addEventListener("click",async e=>{const button=e.target.closest("button");if(!button)return;const id=Number(button.dataset.id),profile=state.clientProfiles.find(item=>item.id===id);try{if(button.classList.contains("preview-client"))await showClientConfiguration(id);if(button.classList.contains("download-client")){window.location.assign(`/api/client-profiles/${id}/download`);setTimeout(()=>refreshClientProfiles().catch(()=>{}),500);}if(button.classList.contains("edit-client"))openClientProfileForm(profile);if(button.classList.contains("delete-client")&&confirm(`Usunąć profil ${profile.name}?`)){await api(`/api/client-profiles/${id}`,{method:"DELETE"});await refreshClientProfiles();toast("Profil klienta usunięty");}}catch(error){toast(error.message);}});
$("#unrecognized-clients").addEventListener("click",e=>{const button=e.target.closest(".create-client-from-address");if(button)openClientProfileForm(null,button.dataset.address);});
$("#client-config-file").addEventListener("change",e=>$("#client-config-content").textContent=state.clientConfigFiles[e.target.value]||"");
$("#close-client-preview").addEventListener("click",()=>$("#client-config-preview").classList.add("hidden"));
$("#copy-client-config").addEventListener("click",async()=>{try{await navigator.clipboard.writeText($("#client-config-content").textContent);toast("Skopiowano zawartość pliku");}catch(error){toast("Przeglądarka nie pozwoliła skopiować pliku");}});
$("#download-client-config").addEventListener("click",()=>{if(state.clientConfigProfile)window.location.assign(`/api/client-profiles/${state.clientConfigProfile.id}/download`);});
$("#automation-form").addEventListener("submit",async e=>{e.preventDefault();const button=e.target.querySelector('button[type="submit"]');setButtonBusy(button,true,"Zapisywanie…");const data=Object.fromEntries([...new FormData(e.target)].map(([k,v])=>[k,Number(v)]));try{const updated=await api("/api/settings",{method:"POST",body:JSON.stringify(data)});state.settings={...state.settings,...updated};$("#automation-message").textContent="Automatyka zapisana.";toast("Ustawienia automatyki zaktualizowane");}catch(err){$("#automation-message").textContent=err.message;}finally{setButtonBusy(button,false);}});
$("#shutdown-policy-form").addEventListener("submit",async e=>{e.preventDefault();const button=e.target.querySelector('button[type="submit"]');setButtonBusy(button,true,"Zapisywanie…");const data=Object.fromEntries(new FormData(e.target));data.client_shutdown_delay_seconds=Number(data.client_shutdown_delay_seconds);data.client_final_delay_seconds=Number(data.client_final_delay_seconds);try{const updated=await api("/api/settings",{method:"POST",body:JSON.stringify(data)});state.settings={...state.settings,...updated};$("#shutdown-policy-message").textContent="Polityka zapisana.";await refreshClientProfiles();toast("Globalna polityka klientów zaktualizowana");}catch(error){$("#shutdown-policy-message").textContent=error.message;}finally{setButtonBusy(button,false);}});
$("#history-settings-form").addEventListener("submit",async e=>{e.preventDefault();const button=e.target.querySelector('button[type="submit"]');setButtonBusy(button,true,"Zapisywanie…");const data=Object.fromEntries([...new FormData(e.target)].map(([k,v])=>[k,Number(v)]));try{const updated=await api("/api/settings",{method:"POST",body:JSON.stringify(data)});state.settings={...state.settings,...updated};$("#history-settings-message").textContent="Ustawienia historii zapisane.";toast("Cena energii i retencja zostały zapisane");loadHistory();}catch(err){$("#history-settings-message").textContent=err.message;}finally{setButtonBusy(button,false);}});
$("#webhook-form").addEventListener("submit",async e=>{e.preventDefault();const button=e.target.querySelector('button[type="submit"]');setButtonBusy(button,true,"Zapisywanie…");const data=Object.fromEntries(new FormData(e.target));if(!data.webhook_secret)delete data.webhook_secret;try{const updated=await api("/api/settings",{method:"POST",body:JSON.stringify(data)});state.settings={...state.settings,...updated};e.target.elements.webhook_secret.value="";$("#webhook-settings-message").textContent="Webhook zapisany.";toast("Ustawienia webhooka zaktualizowane");}catch(err){$("#webhook-settings-message").textContent=err.message;}finally{setButtonBusy(button,false);}});
$("#test-webhook").addEventListener("click",async()=>{const button=$("#test-webhook");setButtonBusy(button,true,"Wysyłanie…");$("#webhook-message").textContent="Wysyłanie wiadomości testowej…";try{await api("/api/webhook/test",{method:"POST",body:"{}"});$("#webhook-message").textContent="Test dostarczony poprawnie.";toast("Webhook działa prawidłowo");}catch(err){$("#webhook-message").textContent=err.message;}finally{setButtonBusy(button,false);}});
async function loadWebhookScenarios(){if(webhookScenariosLoaded)return;const scenarios=await api("/api/webhook/scenarios");const groups=[];for(const scenario of scenarios){let group=groups.find(item=>item.name===scenario.group);if(!group){group={name:scenario.group,items:[]};groups.push(group);}group.items.push(scenario);}$("#webhook-scenarios").innerHTML=groups.map(group=>`<section class="webhook-scenario-group"><h3>${escapeHtml(group.name)}</h3>${group.items.map(scenario=>`<div class="webhook-scenario-row"><span>${escapeHtml(scenario.label)}</span><button class="secondary send-webhook-scenario" type="button" data-scenario="${escapeHtml(scenario.id)}"><i class="ti ti-webhook"></i><span>Wyślij</span></button></div>`).join("")}</section>`).join("");webhookScenariosLoaded=true;}
$("#webhook-scenario-tester").addEventListener("toggle",e=>{if(e.target.open)loadWebhookScenarios().catch(error=>$("#webhook-scenario-message").textContent=error.message);});
$("#webhook-scenarios").addEventListener("click",async e=>{const button=e.target.closest(".send-webhook-scenario");if(!button)return;setButtonBusy(button,true,"Wysyłanie…");const message=$("#webhook-scenario-message");message.textContent="Wysyłanie symulacji…";try{await api(`/api/webhook/test/${button.dataset.scenario}`,{method:"POST",body:"{}"});message.textContent="Wiadomość testowa została dostarczona.";toast("Wysłano testowy scenariusz webhooka");}catch(error){message.textContent=error.message;}finally{setButtonBusy(button,false);}});
function updateClock(){$("#clock").textContent=new Date().toLocaleString("pl-PL",{weekday:"short",hour:"2-digit",minute:"2-digit"});}updateClock();setInterval(updateClock,1000);
setInterval(()=>{if($("#view-statistics").classList.contains("active")&&$("#history-range").value==="3600")loadHistory();},30000);
setInterval(()=>{if($("#app").classList.contains("hidden"))return;if(Date.now()-lastBackendEvent>22000)markBackendOffline();if(!backendConnected)recoverBackend();},5000);
document.addEventListener("visibilitychange",()=>{if(!document.hidden&&$("#app").classList.contains("hidden")===false){if(Date.now()-lastBackendEvent>22000)markBackendOffline();recoverBackend();}});
window.addEventListener("online",()=>{markBackendOffline();recoverBackend();});
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("/service-worker.js",{scope:"/"}).catch(()=>{}));
init().catch(err=>{$("#auth").classList.remove("hidden");$("#auth-error").textContent=err.message;});
